"""
Tor hidden-service config helper.

MessageChain does NOT implement Tor — the external `tor` daemon runs
the protocol.  This helper produces a `torrc` snippet an operator can
paste into their Tor config so clients in censored networks can reach
a validator's RPC via a `.onion` address, bypassing IP-level blocks.

Design rules:
  * Hidden services MUST forward to `127.0.0.1` — binding RPC to
    `0.0.0.0` while also fronting it with a hidden service exposes the
    same endpoint publicly AND privately, which defeats the point and
    makes the operator's real IP trivially correlatable.  We refuse.
  * The helper is pure — no I/O, no Tor control connection, no `stem`
    dependency.  Operator owns the `tor` process; we just generate text.
  * Inputs are validated against shell-/torrc-injection (no newlines in
    paths, port in [1, 65535]) because the output is pasted verbatim
    into a config file by a human.

The generated snippet is a fragment — it does NOT contain `SOCKSPort 0`
or other global tor directives.  The operator appends it to their
existing torrc.
"""

from __future__ import annotations

import ipaddress


__all__ = ["generate_torrc_snippet", "InvalidTorBindError"]


class InvalidTorBindError(ValueError):
    """Raised when the RPC bind address is unsafe for a hidden service.

    A hidden service whose internal target is a public interface would
    expose the validator's RPC both as a public TCP endpoint and as a
    `.onion` — correlating the two trivially deanonymizes the operator.
    The right fix is to bind RPC to loopback (`--rpc-bind 127.0.0.1`,
    the default) and let the hidden service be the only remote path.
    """


_LOOPBACK_NAMES = {"localhost", "127.0.0.1", "::1"}


def _is_loopback(addr: str) -> bool:
    """Return True iff `addr` resolves syntactically to a loopback address.

    No DNS is performed — we accept the string forms an operator would
    reasonably type into `--rpc-bind`.
    """
    if addr in _LOOPBACK_NAMES:
        return True
    try:
        parsed = ipaddress.ip_address(addr)
    except ValueError:
        return False
    return parsed.is_loopback


def generate_torrc_snippet(
    rpc_bind_addr: str,
    rpc_port: int,
    hidden_service_dir: str,
    external_port: int | None = None,
) -> str:
    """Return a torrc snippet fronting the given RPC with a hidden service.

    Parameters
    ----------
    rpc_bind_addr:
        The address `--rpc-bind` is set to on the validator.  MUST be a
        loopback form (127.0.0.1, ::1, localhost).  Any other value
        raises `InvalidTorBindError` — see the module docstring for why.
    rpc_port:
        The TCP port the validator's RPC listens on.  Must be in
        [1, 65535].
    hidden_service_dir:
        Filesystem path where tor will store the hidden-service private
        key and `hostname` file.  Tor creates it on first start.  Must
        be non-empty and contain no newline (to prevent torrc
        injection).
    external_port:
        The port advertised on the `.onion` address.  Defaults to
        `rpc_port` so `http://xxx.onion:9334/` mirrors the local URL.
        Operators who want `http://xxx.onion/` can pass `external_port=80`.

    Returns
    -------
    A multi-line torrc snippet.  Example::

        # MessageChain hidden service — generated by `messagechain gen-tor-config`
        HiddenServiceDir /var/lib/tor/messagechain/
        HiddenServicePort 9334 127.0.0.1:9334
    """
    if not isinstance(rpc_port, int) or not (1 <= rpc_port <= 65535):
        raise ValueError(
            f"rpc_port must be an integer in [1, 65535]; got {rpc_port!r}"
        )
    if external_port is None:
        external_port = rpc_port
    if not isinstance(external_port, int) or not (1 <= external_port <= 65535):
        raise ValueError(
            f"external_port must be an integer in [1, 65535]; got {external_port!r}"
        )

    if not hidden_service_dir or not hidden_service_dir.strip():
        raise ValueError("hidden_service_dir must be a non-empty path")
    if any(ch in hidden_service_dir for ch in ("\n", "\r")):
        raise ValueError(
            "hidden_service_dir must not contain newline characters "
            "(would inject extra torrc directives)"
        )

    if not _is_loopback(rpc_bind_addr):
        raise InvalidTorBindError(
            f"RPC is bound to {rpc_bind_addr!r}; hidden services must "
            "forward to a loopback address (127.0.0.1 / ::1 / localhost). "
            "Restart the node with --rpc-bind 127.0.0.1 before fronting "
            "it with a Tor hidden service."
        )

    # Always route the hidden service to 127.0.0.1 regardless of which
    # loopback form the operator passed — keeps the snippet identical
    # and matches what tor actually needs.
    internal_target = f"127.0.0.1:{rpc_port}"

    return (
        "# MessageChain hidden service — generated by `messagechain gen-tor-config`\n"
        "# Paste into /etc/tor/torrc, restart tor, then read the .onion\n"
        "# hostname from {dir}/hostname and share it with clients.\n"
        "HiddenServiceDir {dir}\n"
        "HiddenServicePort {ext} {internal}\n"
    ).format(
        dir=hidden_service_dir,
        ext=external_port,
        internal=internal_target,
    )
